language: python

env:
  global:
  - GH_REF: github.com/timodonnell/sefara.git
  - secure: "LKOTsxZMfN/NVXW6q/4sWEF4a6w9I1Lw6yJGPPPRYXtTymUfp1jIgaPnADxel1pbvXuFD/9RFTunoVBS/++JIrHPKHHB4TS2Z287aB8RObk/bvUPKFbJzEDL+dO3y0lsjn8g1ySFmF6M3QS9Q3mLWtop4dF01ySmY8YCLeTG74k="

python:
    - "2.7"
    - "3.4"

# command to install dependencies
# for some reason, Sphinx gives an ImportError building the docs without the -e
# option here.
install: "pip install -e ."

script:
    - nosetests

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-gh-pages.sh
    
    
