language: python

env:
  global:
  - GH_REF: github.com/timodonnell/sefara.git
  - secure: "In5yeAKDra0/yVNWBZbCrjAMUyxunGyo0Itcs1mdbuf0TjjnFFi1yOlacsKhDIDkU/j650FgtFSbJ4hUy39U5kUwOi7F0CLuUoTt08IBIY7Fxq9OUpPzDALSZbsmUBwxMsW2x6/qevFXcnQnvdmR+Cbr2GN+QPgTzsA8SJPkz0o="

python:
    - "2.7"
    - "3.4"

# command to install dependencies
# for some reason, Sphinx gives an ImportError building the docs without the -e
# option here.
install: "pip install -e ."

script:
    - nosetests

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-gh-pages.sh
    
    
