language: python

env:
  global:
  - GH_REF: github.com:timodonnell/sefara.git
  - secure: LtLG4uwY3KP+zf2rMc78TtzPNpzFWgnQkXBI6dzDycc+RjSDsstJv6vU1VW3hSGqTFvqgnAJoiOOPJtCZifgydJJL/xPyO1iohHqQVEzKNSddQNrSF2CAnb37iw6zpcIV0YeeqKofb3BggoBzycoi/JI7VMUOdzQCpb5OU1zrwE=

python:
    - "2.7"
    - "3.4"

# command to install dependencies
install: "pip install ."

script:
    - nosetests

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-gh-pages.sh
    
    
    - 
    - pip install Sphinx
    - cd docs
    - make clean
    - make setup
    - make rst
    - make html

    - cd _build
    - touch .nojekyll
    - git init
    - git config user.name "Travis-CI"
    - git config user.email "travis@w3ctag.org"
    - git add .
    - git commit -m "Deploy to GitHub Pages"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
